### ISSUE TITLE
Timeout error: unable to Golemize docker image using gvmkit-build

### ISSUE THREAD

**Issue by zkwarlock** [golemfactory/ya-runtime-vm#81]
Running `gvmkit-build golemfactory/blender:demo` gives me this error.

```sh
pull golemfactory/blender:demo |███████████████| 1 in 16:00.2 (0.00/s)
Docker Image : sha256:c76719083b512020c48290943a01657be55fe08dda234ee43d4b332b2ca66361
Entry Point  : <none>
Working Dir  : /golem/work/
Command      : '/bin/bash'
User         : <none>
Volumes      :

     - /golem/output
     - /golem/resource
     - /golem/work

Env          :

     - PATH=/blender:/usr/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     - BLENDER_MAJOR=2.80
     - BLENDER_VERSION=2.80
     - GLIBC_VERSION=217
     - BLENDER_BZ2_URL=http://download.blender.org/release/Blender2.80/blender-2.80-linux-glibc217-x86_64.tar.bz2

Output File  : golemfactory-blender-demo-c76719083b.gvmi

extracting files |███████████████| 13278 in 1:33.1 (142.57/s)
Traceback (most recent call last):
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.9/3.9.2_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/bin/gvmkit-build", line 8, in <module>
    sys.exit(build())
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/gvmkit_build/build.py", line 181, in build
    builder.convert()
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/gvmkit_build/build.py", line 64, in __exit__
    self._tool.remove(force=True, v=True)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/docker/models/containers.py", line 351, in remove
    return self.client.api.remove_container(self.id, **kwargs)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/docker/api/container.py", line 1009, in remove_container
    res = self._delete(
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/docker/api/client.py", line 245, in _delete
    return self.delete(url, **self._set_request_timeout(kwargs))
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/requests/sessions.py", line 624, in delete
    return self.request('DELETE', url, **kwargs)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/Users/hp/Documents/gitcoin-gr9/golem-tutorial/micmac-golem/compile-docker/venv/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

#### Environment
- Intel MacOS Catalina
- Python 3.9
- gvmkit-build 0.2.5
- Docker 20.10.5: Docker desktop is running on my system. I'm able to spin up containers.

**Comment by mfranciszkiewicz** [comment]
`gvmkit` and the runtime itself are only supported on Linux at the moment, sorry for the inconvenience.
